regions:
- eu-west-1
- us-east-1
- global

account-blocklist:
  # account sto be excluded, takes precedence over accounts list
  # keep prod accounts here for safety and to avoid accidental deletion 
- "000000000000"

accounts:
  # account that needs to be included
  "111111111111": {}

resource-types:
  excludes:
  - S3Bucket
  - S3Object
  - IAMUser
  - IAMUserAccessKey
  - IAMUserPolicy
  - IAMRolePolicy
  - IAMRole
  - IAMPolicy
  - IAMGroup
  - IAMGroupPolicy
  - IAMVirtualMFADevice
  - IAMGroupPolicyAttachment
  - IAMInstanceProfile
  - IAMRolePolicyAttachment
  - IAMInstanceProfileRole
  - IAMLoginProfile
  - IAMUserPolicyAttachment
  - IAMUserGroupAttachment
  - IAMServiceSpecificCredential
  - LambdaFunction
  - LambdaEventSourceMapping
  - EC2Subnet
  - OSPackage
  - EC2DefaultSecurityGroupRule
  - EC2SecurityGroup
  - SNSTopic
  - SNSSubscription
  - SQSQueue